/**
*
* @ Copyright: Copyright (C) Farsus Design. All rights reserved. 
* @ Package: ScarPoX / shortterm SPX
* @ Subpackage: RUNCMS 
* @ License: http://www.gnu.org/copyleft/gpl.html GNU/GPL
* @ Subpackage: ScarPoX ESeditor
* @ ESeditor is based on FCKeditor by Frederico Caldeira Knabben
* @ original authers website http://www.fckeditor.net
*
*/

var NS;if (!(NS=window.parent.__ESeditorNS)) NS=window.parent.__ESeditorNS=new Object();
Array.prototype.addItem=function(A){var i=this.length;this[i]=A;return i;};Array.prototype.indexOf=function(A){for (var i=0;i<this.length;i++){if (this[i]==A) return i;};return-1;};String.prototype.startsWith=function(A){return (this.substr(0,A.length)==A);};String.prototype.endsWith=function(A,B){var C=this.length;var D=A.length;if (D>C) return false;if (B){var E=new RegExp(A+'$','i');return E.test(this);}else return (D==0||this.substr(C-D,D)==A);};String.prototype.remove=function(A,B){var s='';if (A>0) s=this.substring(0,A);if (A+B<this.length) s+=this.substring(A+B,this.length);return s;};String.prototype.trim=function(){return this.replace(/(^\s*)|(\s*$)/g,'');};String.prototype.ltrim=function(){return this.replace(/^\s*/g,'');};String.prototype.rtrim=function(){return this.replace(/\s*$/g,'');};String.prototype.replaceNewLineChars=function(A){return this.replace(/\n/g,A);}
var ES_STATUS_NOTLOADED=window.parent.ES_STATUS_NOTLOADED=0;var ES_STATUS_ACTIVE=window.parent.ES_STATUS_ACTIVE=1;var ES_STATUS_COMPLETE=window.parent.ES_STATUS_COMPLETE=2;var ES_TRISTATE_OFF=window.parent.ES_TRISTATE_OFF=0;var ES_TRISTATE_ON=window.parent.ES_TRISTATE_ON=1;var ES_TRISTATE_DISABLED=window.parent.ES_TRISTATE_DISABLED=-1;var ES_UNKNOWN=window.parent.ES_UNKNOWN=-1000;var ES_TOOLBARITEM_ONLYICON=window.parent.ES_TOOLBARITEM_ONLYICON=0;var ES_TOOLBARITEM_ONLYTEXT=window.parent.ES_TOOLBARITEM_ONLYTEXT=1;var ES_TOOLBARITEM_ICONTEXT=window.parent.ES_TOOLBARITEM_ICONTEXT=2;var ES_EDITMODE_WYSIWYG=window.parent.ES_EDITMODE_WYSIWYG=0;var ES_EDITMODE_SOURCE=window.parent.ES_EDITMODE_SOURCE=1;
var ESBrowserInfo;if (!(ESBrowserInfo=NS.ESBrowserInfo)){ESBrowserInfo=NS.ESBrowserInfo=new Object();var sAgent=navigator.userAgent.toLowerCase();ESBrowserInfo.IsIE=(sAgent.indexOf("msie")!=-1);ESBrowserInfo.IsGecko=!ESBrowserInfo.IsIE;ESBrowserInfo.IsSafari=(sAgent.indexOf("safari")!=-1);ESBrowserInfo.IsNetscape=(sAgent.indexOf("netscape")!=-1);};
var ESScriptLoader=new Object();ESScriptLoader.IsLoading=false;ESScriptLoader.Queue=new Array();ESScriptLoader.AddScript=function(A){ESScriptLoader.Queue[ESScriptLoader.Queue.length]=A;if (!this.IsLoading) this.CheckQueue();};ESScriptLoader.CheckQueue=function(){if (this.Queue.length>0){this.IsLoading=true;var A=this.Queue[0];var B=new Array();for (i=1;i<this.Queue.length;i++) B[i-1]=this.Queue[i];this.Queue=B;this.LoadFile(A);}else{this.IsLoading=false;if (this.OnEmpty) this.OnEmpty();};};ESScriptLoader.LoadFile=function(A){var e;if (A.lastIndexOf('.css')>0){e=document.createElement('LINK');e.rel='stylesheet';e.type='text/css';}else{e=document.createElement("script");e.type="text/javascript";};document.getElementsByTagName("head")[0].appendChild(e);if (e.tagName=='LINK'){if (ESBrowserInfo.IsIE) e.onload=ESScriptLoader_OnLoad;else ESScriptLoader.CheckQueue();e.href=A;}else{e.onload=e.onreadystatechange=ESScriptLoader_OnLoad;e.src=A;};};function ESScriptLoader_OnLoad(){if (this.tagName=='LINK'||!this.readyState||this.readyState=='loaded') ESScriptLoader.CheckQueue();}
var ESURLParams=new Object();var aParams=document.location.search.substr(1).split('&');for (var i=0;i<aParams.length;i++){var aParam=aParams[i].split('=');var sParamName=aParam[0];var sParamValue=aParam[1];ESURLParams[sParamName]=sParamValue;}
var ES=new Object();ES.Name=ESURLParams['InstanceName'];ES.Status=ES_STATUS_NOTLOADED;ES.EditMode=ES_EDITMODE_WYSIWYG;ES.LoadLinkedFile=function(){var A=window.parent.document;var B=A.getElementById(ES.Name);var C=A.getElementsByName(ES.Name);var i=0;while (B||i==0){if (B&&(B.tagName=='INPUT'||B.tagName=='TEXTAREA')){ES.LinkedField=B;break;};B=C[i++];};};ES.LoadLinkedFile();var ESTempBin=new Object();ESTempBin.Elements=new Array();ESTempBin.AddElement=function(A){var B=ESTempBin.Elements.length;ESTempBin.Elements[B]=A;return B;};ESTempBin.RemoveElement=function(A){var e=ESTempBin.Elements[A];ESTempBin.Elements[A]=null;return e;};ESTempBin.Reset=function(){var i=0;while (i<ESTempBin.Elements.length) ESTempBin.Elements[i++]==null;ESTempBin.Elements.length=0;}
var ESConfig=ES.Config=new Object();if (document.location.protocol=='file:'){ESConfig.BasePath=unescape(document.location.pathname.substr(1));ESConfig.BasePath=ESConfig.BasePath.replace(/\\/gi, '/');ESConfig.BasePath='file://'+ESConfig.BasePath.substring(0,ESConfig.BasePath.lastIndexOf('/')+1);}else{ESConfig.BasePath=document.location.pathname.substring(0,document.location.pathname.lastIndexOf('/')+1);ESConfig.FullBasePath=document.location.protocol+'//'+document.location.host+ESConfig.BasePath;};ESConfig.EditorPath=ESConfig.BasePath.replace(/editor\/$/,'');try{ESConfig.ScreenWidth=screen.width;ESConfig.ScreenHeight=screen.height;}catch (e){ESConfig.ScreenWidth=800;ESConfig.ScreenHeight=600;};ESConfig.ProcessHiddenField=function(){this.PageConfig=new Object();var A=window.parent.document.getElementById(ES.Name+'___Config');if (!A) return;var B=A.value.split('&');for (var i=0;i<B.length;i++){if (B[i].length==0) continue;var C=B[i].split('=');var D=unescape(C[0]);var E=unescape(C[1]);if (D=='CustomConfigurationsPath') ESConfig[D]=E;else if (E.toLowerCase()=="true") this.PageConfig[D]=true;else if (E.toLowerCase()=="false") this.PageConfig[D]=false;else if (!isNaN(E)) this.PageConfig[D]=parseInt(E);else this.PageConfig[D]=E;};};ESConfig.LoadPageConfig=function(){for (var A in this.PageConfig) ESConfig[A]=this.PageConfig[A];};ESConfig.ToolbarSets=new Object();ESConfig.Plugins=new Object();ESConfig.Plugins.Items=new Array();ESConfig.Plugins.Add=function(A,B,C){ESConfig.Plugins.Items.addItem([A,B,C]);};ESConfig.ProtectedSource=new Object();ESConfig.ProtectedSource.RegexEntries=new Array();ESConfig.ProtectedSource.Add=function(A){this.RegexEntries.addItem(A);};ESConfig.ProtectedSource.Protect=function(A){function _Replace(protectedSource){var B=ESTempBin.AddElement(protectedSource);return '<!--{PS..'+B+'}-->';};for (var i=0;i<this.RegexEntries.length;i++){A=A.replace(this.RegexEntries[i],_Replace);};return A;};ESConfig.ProtectedSource.Revert=function(A,B){function _Replace(m,opener,index){var C=B?ESTempBin.RemoveElement(index):ESTempBin.Elements[index];return ESConfig.ProtectedSource.Revert(C,B);};return A.replace(/(<|&lt;)!--\{PS..(\d+)\}--(>|&gt;)/g,_Replace);};ESConfig.ProtectedSource.Add(/<!--[\s\S]*?-->/g);
var ESeditorAPI;function ESeditorAPI_GetInstance(instanceName){return this.__Instances[instanceName];};if (!window.parent.ESeditorAPI){ESeditorAPI=window.parent.ESeditorAPI=new Object();ESeditorAPI.__Instances=new Object();ESeditorAPI.Version='2.2';ESeditorAPI.GetInstance=ESeditorAPI_GetInstance;}else ESeditorAPI=window.parent.ESeditorAPI;ESeditorAPI.__Instances[ES.Name]=ES;
function Window_OnContextMenu(e){if (e) e.preventDefault();else{if (event.srcElement==document.getElementById('eSourceField')) return true;};return false;};window.document.oncontextmenu=Window_OnContextMenu;if (ESBrowserInfo.IsGecko){function Window_OnResize(){var oFrame=document.getElementById('eEditorArea');oFrame.height=0;var oCell=document.getElementById(ES.EditMode==ES_EDITMODE_WYSIWYG?'eWysiwygCell':'eSource');var iHeight=oCell.offsetHeight;oFrame.height=iHeight-2;};window.onresize=Window_OnResize;};if (ESBrowserInfo.IsIE){var aCleanupDocs=new Array();aCleanupDocs[0]=document;function Window_OnBeforeUnload(){var d,e;var j=0;while ((d=aCleanupDocs[j++])){var i=0;while ((e=d.getElementsByTagName("DIV").item(i++))){if (e.ESToolbarButton) e.ESToolbarButton=null;if (e.ESSpecialCombo) e.ESSpecialCombo=null;if (e.Command) e.Command=null;};i=0;while ((e=d.getElementsByTagName("TR").item(i++))){if (e.ESContextMenuItem) e.ESContextMenuItem=null;};aCleanupDocs[j]=null;};if (typeof(ESTempBin)!='undefined') ESTempBin.Reset();};window.attachEvent("onunload",Window_OnBeforeUnload);};function Window_OnLoad(){if (ESBrowserInfo.IsNetscape) document.getElementById('eWysiwygCell').style.paddingRight='2px';LoadConfigFile();};window.onload=Window_OnLoad;function LoadConfigFile(){ESScriptLoader.OnEmpty=ProcessHiddenField;ESScriptLoader.AddScript('../esconfig.php');};function ProcessHiddenField(){ESConfig.ProcessHiddenField();LoadCustomConfigFile();};function LoadCustomConfigFile(){if (ESConfig.CustomConfigurationsPath.length>0){ESScriptLoader.OnEmpty=LoadPageConfig;ESScriptLoader.AddScript(ESConfig.CustomConfigurationsPath);}else{LoadPageConfig();};};function LoadPageConfig(){ESConfig.LoadPageConfig();if (ESConfig.AllowQueryStringDebug&&(/esdebug=true/i).test(window.top.location.search)) ESConfig.Debug=true;LoadStyles();};function LoadStyles(){ESScriptLoader.OnEmpty=LoadScripts;ESScriptLoader.AddScript(ESConfig.SkinPath+'es_editor.css');ESScriptLoader.AddScript(ESConfig.SkinPath+'es_contextmenu.css');};function LoadScripts(){ESScriptLoader.OnEmpty=null;if (ESBrowserInfo.IsIE) ESScriptLoader.AddScript('js/eseditorcode_ie_1.js');else ESScriptLoader.AddScript('js/eseditorcode_gecko_1.js');};function LoadLanguageFile(){ESScriptLoader.OnEmpty=LoadEditor;ESScriptLoader.AddScript('lang/'+ESLanguageManager.ActiveLanguage.Code+'.js');};function LoadEditor(){ESScriptLoader.OnEmpty=null;if (ESLang) window.document.dir=ESLang.Dir;ES.StartEditor();}
